### ISSUE TITLE
Allow optimizing for format, but not size

### ISSUE THREAD

**Issue by Cretezy** [marlokessler/strapi-plugin-image-optimizer#11]
We have images which we don't care about optimizing in size, however generating in better formats (Like AVIF) is important to us.

Does it make sense to add to this plugin? I can contribute a PR.

**Comment by marlokessler** [comment]
Hi @Cretezy, this seems like a valid use case. It would be awesome if you could contribute the feature as a PR.

I think the best way to do this is by allowing image size objects without a width or height where only the new formats are then generated, e.g.:
```json
sizes: [
    {
      name: "original",
    },
]
```

What do you think?

**Comment by Cretezy** [comment]
Yes I think that makes sense.

I have never developed a Strapi plugin before. Could you add a CONTRIBUTING.md file, or at least some instructions to get started locally? Thanks a lot.
