### ISSUE TITLE
Strapi-plugin-image-optimizer error on updating to strapi v4.11

### ISSUE THREAD

**Issue by mervin-work** [marlokessler/strapi-plugin-image-optimizer#22]
Hi, I encoutered error on updating strapi version 4.11.4. when running `npm run develop`

Error: Could not load js config file D:\<Folder>\<Project>\node_modules\strapi-plugin-image-optimizer\strapi-server.js: Cannot find module '@strapi/utils/lib/file'

**Comment by nixjs** [comment]
Me too! The new version had `@strapi/utils/dist/file` stead of `@strapi/utils/lib/file`.

**Comment by VilionVonSqrt** [comment]
Same problem at version 4.6.2

**Comment by marlokessler** [comment]
Hi @mervin-work and @nixjs, thank you for reporting this. The bug was fixed and released with [v2.1.1](https://github.com/marlokessler/strapi-plugin-image-optimizer/releases/tag/v2.1.1). Could you please verify if it works?

**Comment by mervin-work** [comment]
hi @marlokessler, yep, it is working again! thank you!

**Comment by marlokessler** [comment]
Perfect, thank you!
