### ISSUE TITLE
error: isImage is not a function

### ISSUE THREAD

**Issue by AndreasFaust** [marlokessler/strapi-plugin-image-optimizer#23]
Thank you for creating this module!
Unfortunately I cannot get it to run. Following your instructions I end up receiving this error as soon as I try to upload an image:
```
TypeError: isImage is not a function
````
```
node_modules/@strapi/plugin-upload/server/services/upload.js:136:1
```

Strapi’s `upload`-Service tries to import `isImage` from `plugin.services["image-manipulation"]`, but fails because it gets overridden by this plugin’s service, which does not contain `isImage`.

**Comment by bogdaaamn** [comment]
Is there a way to fix this without using `import` or switching to TypeScript? 😭

**Comment by tudor-sv** [comment]
PS: After some digging and debugging, I've figured out the cause of the problem: 
```
const imageOptimizerService = require("strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service").default;

module.exports = (plugin) => {
  plugin.services["image-manipulation"] = imageOptimizerService;
  return plugin;
};
```
Notice the **.default** at the end, when using require()
It works now.
Please add this to the docs ( "2. Extend Strapi's upload plugin" section ), in case others might bump into the same issue when figuring out how to import/require in the JS version of Strapi.

Thanks!
