### ISSUE TITLE
Optimizer Integration with Strapi S3 Plugin

### ISSUE THREAD

**Issue by faraasat** [marlokessler/strapi-plugin-image-optimizer#28]
Want to know how to integrate this optimization plugin with `"@strapi/provider-upload-aws-s3"` plugin because this plugin is not working with the s3 uploads!

**Comment by sarikajadhavneo** [comment]
have you received any solution over this?

**Comment by faraasat** [comment]
> have you received any solution over this?

It automatically started working!

**Comment by sarikajadhavneo** [comment]
Could you plz chk this https://github.com/marlokessler/strapi-plugin-image-optimizer/issues/32, Any suggestion
