### ISSUE TITLE
Could not load js config file D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\strapi-server.js: Cannot find module '@strapi/utils/dist/file'

### ISSUE THREAD

**Issue by ErikHarutyunyan** [marlokessler/strapi-plugin-image-optimizer#37]
Error: Could not load js config file D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\strapi-server.js: Cannot find module '@strapi/utils/dist/file'   │    
│   Require stack:                                                                                                                                                                 │    
│   - D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\dist\server\services\image-optimizer-service.js                                                     │    
│   - D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\dist\server\services\index.js                                                                       │    
│   - D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\dist\server\index.js                                                                                │    
│   - D:\projects\strapi\my-project\node_modules\strapi-plugin-image-optimizer\strapi-server.js                                                                                    │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\utils\dist\index.js                                                                                                       │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\commands\actions\admin\create-user\action.js                                                                  │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\commands\actions\admin\create-user\command.js                                                                 │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\commands\index.js                                                                                             │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\cli.js                                                                                                        │    
│   - D:\projects\strapi\my-project\node_modules\@strapi\strapi\bin\strapi.js                                                                                                      │    
│       at loadJsFile (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\core\app-configuration\load-config-file.js:18:13)                                            │    
│       at Module.loadFile (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\core\app-configuration\load-config-file.js:37:14)                                       │    
│       at Object.loadPlugins (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\core\loaders\plugins\index.js:90:41)                                                 │    
│       at async Strapi.loadPlugins (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\Strapi.js:310:5)                                                               │    
│       at async Promise.all (index 3)                                                                                                                                             │    
│       at async Strapi.register (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\Strapi.js:340:5)                                                                  │    
│       at async Strapi.load (D:\projects\strapi\my-project\node_modules\@strapi\strapi\dist\Strapi.js:424:5)                                                                      │    
│       at async Object.develop (D:\projects\strapi\my-project\node_modules\@strapi\admin\dist\_chunks\index-ffd2f664.js:1245:28)                                                  │    
│       at async develop (D:\projects\strapi\my-project\node_modules\@strapi\admin\dist\_chunks\develop-da585b1e.js:52:5)                                                          │    
│       at async Command.parseAsync (D:\projects\strapi\my-project\node_modules\commander\lib\command.js:923:5) 

**I can't use the plugin, can you tell me what it is?**

![image](https://github.com/marlokessler/strapi-plugin-image-optimizer/assets/82722153/1128cd60-0066-4e59-afe6-76bd737a43f2)

![image](https://github.com/marlokessler/strapi-plugin-image-optimizer/assets/82722153/8930cffb-2560-4360-894b-01227c5d7a31)

![image](https://github.com/marlokessler/strapi-plugin-image-optimizer/assets/82722153/ecd99f45-00f8-4870-9e93-2e66dec5bbbb)

![image](https://github.com/marlokessler/strapi-plugin-image-optimizer/assets/82722153/6a329eea-701f-40bb-ad5b-a18ec865ec20)

**Comment by ErikHarutyunyan** [comment]
![image](https://github.com/marlokessler/strapi-plugin-image-optimizer/assets/82722153/94eafa25-3809-488d-be35-1ff378ea7ad1)

**Comment by e115sa** [comment]
I have the same problem on strapi v4.14.5 in out project.

**Comment by mikeacre** [comment]
Also having this issue.

**Comment by pietropietro** [comment]
same issue

**Comment by igghera** [comment]
Same error here, unable to use the plugin

**Comment by welschmoor** [comment]
Same

**Comment by Rupsnigdha** [comment]
same issue

**Comment by y-nk** [comment]
adding `@strapi/core:*` breaks older installs. this will pull the latest core, which pulls @strapi/data-transfer, @strapi/admin and ultimately @strapi/strapi@latest... even if you'd pinned strapi@4.14 at root level. better pin the core version to something tangible 🙏
