### ISSUE TITLE
Optimize images with extension in ignore case maner

### ISSUE THREAD

**Issue by yarikwest** [marlokessler/strapi-plugin-image-optimizer#9]
While uploading image with extension in not lower case (e.g. "IMAGE.JPG"), optimization doesn't work

**Comment by marlokessler** [comment]
Fixed with #10 and released in [v2.0.1](https://github.com/marlokessler/strapi-plugin-image-optimizer/releases/tag/v2.0.1)

**Comment by marlokessler** [comment]
@yarikwest Thank you for your contribution
